title: Sutiwas Jitsopak
logo: /assets/img/profile_pic.png
description: Experienced professional transitioning into the Data Science and AI space, combining analytical thinking with technical expertise to build end-to-end solutions. Passionate about developing Machine Learning models and implementing them to drive business value.
show_downloads: true
theme: jekyll-theme-minimal
