title: Sutiwas Jitsopak
logo: /assets/img/profile_pic.png
description: Experienced professional transitioning into the data and AI space, combining analytical thinking with technical expertise to build end-to-end data solutions. Passionate about extracting meaningful insights from complex datasets and implementing innovative AI applications that drive business value.
show_downloads: true
theme: jekyll-theme-minimal
